Perbaiki crash kurung siku bersarang pada teks hari ospek
Penyebab crash yang dilaporkan pemain:
  File "game/script.rpy", line 1200
    "[ Hari [day] dari [ospek_tracker.total_ospek_days] ]"
  SyntaxError: invalid syntax

Ren'Py membaca "[ ... ]" sebagai ekspresi Python, sehingga kurung siku
bersarang membuat seluruh isinya dievaluasi sebagai kode Python dan
gagal. Diperbaiki menjadi satu tingkat kurung saja:

  "Hari [day] dari [ospek_tracker.total_ospek_days]"

Bug ini sudah ada sejak commit 3a14c56 dan lolos dari pengujian
sebelumnya karena uji boot tidak pernah masuk ke `label start`, sehingga
teks dialog tidak pernah dievaluasi.

Pengujian yang ditambahkan:
- Validator statis untuk semua interpolasi [expr] di script.rpy
  (memeriksa penyeimbangan kurung + compile() setiap ekspresi)
- Uji end-to-end headless yang memainkan alur sungguhan dari `label
  start` sampai `final_evaluation`, menjawab semua menu dan input
  otomatis, lalu menuliskan ringkasan hasil ke berkas
- Uji dilakukan pada 3 jalur berbeda (akademik, sosial, pasif);
  semuanya selesai tanpa error
- Uji dibuktikan mampu menangkap bug: versi lama dikembalikan dan uji
  gagal dengan SyntaxError yang sama seperti laporan pemain